name: deploy

on:
  push:
    branches:
      - main


jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USER }} 
          script: |
            PID=$(lsof -t -i:8080)
            if [ -z "$PID" ]; then
              echo "No process is running on port 8080"
            else
              echo "Killing process $PID"
              kill -9 $PID
            fi
            cd q_feed_backend
            git pull
            sh gradlew build
            cd build/libs
            nohup java -jar loginlogic-0.0.1-SNAPSHOT.jar > ~/q_feed_backend/nohup.out 2>&1 &
